# GeoMorph version number

set (GEOMORPH_MAJOR 0)
set (GEOMORPH_MINOR 60)
set (GEOMORPH_PATCH 1)
set (GEOMORPH_VERSION "${GEOMORPH_MAJOR}.${GEOMORPH_MINOR}.${GEOMORPH_PATCH}" )

# GEOMORPH release date

set (GEOMORPH_RELEASE "2012-08-01")
